# Generated by Django 5.1.4 on 2024-12-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_bio_profile_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='dob',
        ),
    ]
